trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

variables:
  TF_WORKING_DIR: "terraform"

steps:
  - checkout: self

  - task: UseTerraform@0
    inputs:
      terraformVersion: "latest"

  - script: |
      echo "$(GCP_CREDENTIALS)" > $(Agent.TempDirectory)/gcp_credentials.json
    displayName: "Criar arquivo de credenciais GCP"

  - script: |
      gcloud auth activate-service-account --key-file=$(Agent.TempDirectory)/gcp_credentials.json
    displayName: "Autenticar no GCP"

  - script: terraform init $(TF_WORKING_DIR)
    displayName: "Terraform Init"

  - script: terraform plan $(TF_WORKING_DIR)
    displayName: "Terraform Plan"

  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
      - script: terraform apply -auto-approve $(TF_WORKING_DIR)
        displayName: "Terraform Apply"
