name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # - name: Set GOOGLE_CREDENTIALS environment variable for Terraform
      #   run: echo "GOOGLE_CREDENTIALS =${{ secrets.GCP_CREDENTIALS }}" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Destroy
        working-directory: terraform/
        run: terraform destroy -auto-approve
